### PR TITLE
Update VPN Client documentation

### PR DESCRIPTION
**Pull request by ramereth**
This has been updated and verified to work on the platforms mentioned. This should hopefully workaround issues folks may have run into.

Signed-off-by: Lance Albertson <lance@osuosl.org>

### CODE REVIEW

**Comment by osuosl-manatee** [comment]
This PR has been automatically built and can be viewed here: https://wiki-125.staging.osuosl.org

**Comment by madmax-codewarrior-0** [comment]
@ramereth I know at least when I've been running EL8 versions and Fedora, that I have to add the following to my config, to get DNS working: 

```
# Up-Down Scripts:
up /usr/share/doc/openvpn/contrib/pull-resolv-conf/client.up
up-restart
plugin openvpn-plugin-down-root.so "/etc/openvpn/client.down"
down /usr/share/doc/openvpn/contrib/pull-resolv-conf/client.down
```

Sometimes there's an update that will reset the perms on those scripts as well, so they have to be reset back to 755.

**Comment by ramereth** [comment]
Oops, I forgot to add docs on the DNS side of it (if you're not using NetworkManager)

**Comment by ArtofBugs** [comment]
+1 for Ubuntu!
(I am still having some issues but I think it's a problem on my side; I was able to get both the Network Manager and the systemctl service running.)

**Comment by ramereth** [comment]
I'm going to call this ready and go ahead and merge this.

**Pull request merged**
