### PR TITLE
Write docs on writing docs in developer workflow

### PR DESCRIPTION
**Pull request by iankronquist**
Includes things I've learned at the Write The Docs conference.

### CODE REVIEW

**Comment by jordane** [comment]
This seems a bit out of context on this page, as the page doesn't really talk as much about developer workflow. It's more of 'here is a smattering of stuff you should know but arent all entirely related'. I think it would make sense to have a page on documentation best practices, style guidelines, and such, and then link that page here with some context.

**Comment by iankronquist** [comment]
I think writing docs should be part of the developer workflow. Maybe it belongs on its own page. I stuck it here because it made more sense here than elsewhere.

**Comment by jordane** [comment]
I agree it is part of the developer workflow, I just don't think this page really focuses on developer workflow at all.

**Comment by iankronquist** [comment]
I disagree. This does not describe the tight loop of "pop a bug off the stack, fix it, make a PR, get it merged, repeat", but rather the process of writing a project from negotiating specifications with a client, to deployment (page 3). It also covers all of the tools we use along the way. It could probably be made more focused and improved, but that belongs in a new issue.

**Comment by jordane** [comment]
@iankronquist For example, What does GSoC have to do with the development workflow?

**Comment by iankronquist** [comment]
It is tangentially related, and we should write that down somewhere. I wasn't terribly happy putting it there, but new people need to see that "we do this thing called GSoC, that's part of your job over the Summer. Please don't surprise the GSoC students."

**Comment by jordane** [comment]
@iankronquist so can we agree that these docs are more for the lifecycle of a project, and not for the daily workflow of a specific developer?

**Comment by iankronquist** [comment]
Yes, that is correct.

**Comment by jordane** [comment]
@iankronquist Okay. Maybe it would make sense to clarify that in the title somewhere? If so, I'll open an issue for it.

**Comment by iankronquist** [comment]
@jordane should I close this or do you think this is still worthwhile?

**Comment by jordane** [comment]
@iankronquist I think it's still worthwhile.

**Comment by iankronquist** [comment]
@jordane What would you like me to do with it in that case? Is there anything which needs to be fixed?

**Pull request closed without merging**
