### PR TITLE
Update jenkins-docker information

### PR DESCRIPTION
**Pull request by Justin-Fernbaugh**

### CODE REVIEW

**Comment by Justin-Fernbaugh** [comment]
@ramereth Would these changes be sufficient enough of a disclaimer or should the screenshot images be updated to a non osuosl docker image?

**Comment by ramereth** [comment]
@junaruga does this work you think?

**Comment by ramereth** [comment]
@Justin-Fernbaugh do you think you could update the screenshot images? I think that would be very helpful.

**Comment by Justin-Fernbaugh** [comment]
@junaruga @ramereth I was able to update the screenshot images for the docs. The example docker image is now non osuosl to show it's not required. Let me know if it all looks good or if anything else is preferred !

**Comment by ramereth** [comment]
@Justin-Fernbaugh can you please use `optipng` to reduce the size of the images?

**Comment by Justin-Fernbaugh** [comment]
> @Justin-Fernbaugh can you please use `optipng` to reduce the size of the images?

Just pushed changes for optimizing the images.

**Review by ramereth — APPROVED** [review]

**Pull request merged**
