### PR TITLE
Update wiki on creating Jenkins jobs using Docker

### PR DESCRIPTION
**Pull request by khashf**
Changes include:

- Remove out-of-date sections "Set label to restrict where the job runs"
- Add more images pointing user to relevant options on the UI
- Make it clear to the user where to access and what to do once they are
granted permission to use (via ticket)

Direct link: https://wiki-48.staging.osuosl.org/powerci/docker.html

Card: https://trello.com/c/cAMYLEym 
Relevant ticket: https://support.osuosl.org/Ticket/Display.html?id=31265

### CODE REVIEW

**Comment by osuosl-manatee** [comment]
This PR has been automatically built and can be viewed here: https://wiki-48.staging.osuosl.org

**Comment by osuosl-manatee** [comment]
This PR has been automatically built and can be viewed here: https://wiki-48.staging.osuosl.org

**Comment by ramereth** [comment]
@khashf can you please send this staging link to the user on the ticket and get their feedback? You might point them to this PR so they can provide direct feedback.

**Comment by osuosl-manatee** [comment]
This PR has been automatically built and can be viewed here: https://wiki-48.staging.osuosl.org

**Comment by osuosl-manatee** [comment]
This PR has been automatically built and can be viewed here: https://wiki-48.staging.osuosl.org

**Comment by martin-frbg** [comment]
Thanks, this looks much better already. 
I am not entirely convinced that linking to exteral sources for the github integration setup is such a good idea - those urls may change or go away at any point in the future. Also half of it will typically be dedicated to installing the plugin itself (and its requirements)  and the other half seems unlikely to match the exact layout of your osuosl web interface. (E.g. adding credentials - I bet alll of this is obvious to anybody who has worked with this system before, but those are not the people who would consult the wiki in the first place)

**Pull request merged**
