### PR TITLE
WIP test rsync copy and pr build

### PR DESCRIPTION
**Pull request by Kennric**

### CODE REVIEW

**Comment by osuosl-manatee** [comment]
This PR has been automatically built and can be viewed here: http://wiki-30.staging.osuosl.org

**Comment by osuosl-manatee** [comment]
This PR has been automatically built and can be viewed here: http://wiki-30.staging.osuosl.org

**Comment by osuosl-manatee** [comment]
This PR has been automatically built and can be viewed here: http://wiki-30.staging.osuosl.org

**Comment by osuosl-manatee** [comment]
This PR has been automatically built and can be viewed here: http://wiki-30.staging.osuosl.org

**Comment by Kennric** [comment]
@ramereth, @jldugger small changes for compatibility with Jenkins PR autobuild

**Pull request merged**
